### ISSUE TITLE
5.1.12 breaks the package when using with Jest

### ISSUE THREAD

**Issue by risker** [zrrrzzt/html-validator#205]
When updating from 5.1.11 to 5.1.12 the validation stops working. It returns with the error:
> Error 400 Bad request. Valid requests must include a User-Agent header.

I guess the UA change in the latest patch is at fault?

Usage - should be pretty standard, we run a local instance of the W3C validator in Docker:
```js
const options = {
    data: html,
    format: 'text',
    validator: 'http://localhost:8888',
};

const result = await validator(options);
```

**Comment by zrrrzzt** [comment]
I'll look into it.
Do you have a link to your docker so I can recreate the environment?

**Comment by risker** [comment]
I'm afraid I don't - but it failed on us in Bitbucket Pipelines CI (that should be a pretty basic wrapper over docker-compose) with the following config:
```
image: node:12
definitions:
  services:
    vnu:
      image: validator/validator:20.3.16
pipelines:
  default:
    - step:
      name: test:node
      services:
        - vnu
      script:
        - npm ci
        - npm test
```
We're using the official image with no additional configuration.  `npm test` runs the validation tests via jest using the config in the original comment, but I think that should not matter.
